version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: students-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    image: students-api
    container_name: students-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: school
    depends_on:
      - mysql

volumes:
  mysql_data:
